apiVersion: v1
kind: PersistentVolume
metadata:
  name: laion-pvc-pv
  namespace: qa
spec:
  capacity:
    storage: 100Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: new-local-path
  local:
    path: /tmp
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - 4am-node15
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: laion-pvc
  namespace: qa
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: new-local-path
  volumeName: laion-pvc-pv
  resources:
    requests:
      storage: 100Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: laion-test-1
  namespace: qa
spec:
  nodeName: 4am-node15
  containers:
    - name: main
      image: 'harbor.milvus.io/qa/fouram:1.1'
      imagePullPolicy: IfNotPresent
      command:
        - /bin/bash
        - '-c'
      args:
        - "while :; do echo '.'; sleep 5 ; done"
      resources:
        limits:
         cpu: "12"
         nvidia.com/gpu: "2"
         memory: 16Gi
        requests:
         cpu: "12"
         nvidia.com/gpu: "2"
         memory: 16Gi
      volumeMounts:
        - mountPath: /test
          name: db-data-path
        - name: local-persistent-storage
          mountPath: /tmp
  volumes:
    - name: db-data-path
      nfs:
        path: /volume1/test
        server: 172.16.70.249
    - name: local-persistent-storage
      persistentVolumeClaim:
        claimName: laion-pvc
#  tolerations:
#    - key: "node-role.kubernetes.io/gpu"
#      operator: "Exists"
#      effect: "NoSchedule"
#  nodeSelector:
#    "node-role.kubernetes.io/gpu": ""